---
# tasks file for common
# - name: update packages
#   yum:
- name: install utilities
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - tree
    - git
    - unzip
    
