---
# tasks file for webserver
- name: installing nginx
  yum: 
    name: nginx
    state: present
  notify:
  - start nginx
- file:
    path: /etc/nginx/sites-available
    state: directory
- template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
  notify: 
  - restart nginx

